### ISSUE TITLE
生产环境Redis连接并无验证密码

### ISSUE THREAD

**Issue by ioiioo** [tangaiyun/spring-cloud-microservice-ratelimiter#3]
https://github.com/tangaiyun/spring-cloud-microservice-ratelimiter/blob/098a1720168795cf9d42e5bc7262cf10cd295568/src/main/java/com/tay/ratelimitersample/ratelimiter/RedisConfig.java#L44

这一步可以考虑添加上redis无密码连接的情况，先不讨论这样安全与否的问题，
如果redis无须密码进行验证可以考虑如下配置(将password置为null，不然会连不上redis)：
```
  redis:
    host: 192.168.1.1
    port: 6379
    password:
    timeout: 2000
```

com.tay.ratelimitersample.ratelimiter.RedisConfig#redisPoolFactory修改：
```
if(StringUtils.isEmpty(password)){
			password = null;
		}
```
